### ISSUE TITLE
Read themes file from folder “Thems” instead of folder “CodeCompletion”

### ISSUE THREAD

**Issue by suliveevil** [blach/Textastic-Customization#7]
Read themes files from folder “CodeCompletion/Thems/” instead of folder “CodeCompletion/”

**Comment by blach** [comment]
Currently themes are read from "Local Files/#Textastic/". Do you want it to be read from "Local Files/#Textastic/Themes/" instead? Why?

**Comment by suliveevil** [comment]
codecompletion.json is in CodeCompletion/
template.json is in Template/
I just want those theme.tmTheme files in the same pattern😂
