### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by suliveevil** [blach/Textastic-Customization#8]
![Text Alignment Problem](https://user-images.githubusercontent.com/35763237/81427190-05168680-918d-11ea-85b5-8b4b3362bd67.jpeg)

Is this problem caused by font or other setting？
Thank you very much.

**Comment by blach** [comment]
This is because the UI uses a proportional font so characters do not have the same width. Does it help if you try to separate it with tabs like ".vi\t\t- VimScript"?

**Comment by suliveevil** [comment]
Wow, another trick get!
Thank you ☺️ ☺️ ☺️
